fix: let nrwl workspace migrate fail
ng-easy/renovate-config pull request #374
Opened 2022-12-07 09:08 UTC by WolfSoko

ref: #373

2022-12-07 09:36 UTC, WolfSoko commented
I'm missing an entry for `nx migrate --run-migrations` in allowedPostUpdateScripts. Is it missing by accident? 
Seems to work anyway.

2022-12-08 16:24 UTC, samuelfernandez commented
> I'm missing an entry for `nx migrate --run-migrations` in allowedPostUpdateScripts. Is it missing by accident? Seems to work anyway.

Thanks @WolfSoko for spotting this and contributing the PR. The post update script is [here](https://github.com/ng-easy/renovate-config/blob/main/renovate.config.js#L22) would you please update it as well? With that it would be ready to merge

2022-12-08 16:25 UTC, samuelfernandez commented on nrwlWorkspace.json
> +          "[ -f migrations.json ] && npx --no-install nx migrate --run-migrations=migrations.json",
Could you please add this to [`allowedPostUpgradeCommands`](https://github.com/ng-easy/renovate-config/blob/main/renovate.config.js#L15)? Thanks!

2022-12-08 19:48 UTC, WolfSoko commented on nrwlWorkspace.json
> +          "[ -f migrations.json ] && npx --no-install nx migrate --run-migrations=migrations.json",
done, please have a look again

2022-12-09 16:37 UTC, samuelfernandez requested changes

2022-12-09 16:37 UTC, samuelfernandez commented on renovate.config.js
> +    '^\\[ -f migrations\\.json ] && npx --no-install nx migrate --run-migrations=migrations\\.json$',
```suggestion
    '^\\[ -f migrations\\.json \\] && npx --no-install nx migrate --run-migrations=migrations\\.json$',
```

2022-12-09 16:38 UTC, merged

2022-12-10 05:10 UTC, samuelfernandez commented
:tada: This PR is included in version 3.3.2 :tada:

The release is available on [GitHub release](https://github.com/ng-easy/renovate-config/releases/tag/v3.3.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-01-02 09:22 UTC, WolfSoko commented
@samuelfernandez I think my proposed solution does not work. Somehow the task always fails. With 

`Command failed: [ -f migrations.json ] && npx --no-install nx migrate --run-migrations=migrations.json`

Seems like it is a problem with the [ -f migrations.json ] part. 

Should we revert this? Or inveset time into  a working solution?